### ISSUE TITLE
Add litter level accessory

### ISSUE THREAD

**Issue by caleefulling** [rylee-s/Homebridge-Litter-Robot-4#5]
My Whiskers app doesn't send me notifications about low litter levels, despite having them turned on. As a result there have been several times it got very low without me realizing it. I can go into the app and check, or check on it in person if I'm home, but I'd love to be able to automate this.

Would it be possible to surface the litter level data similar to how you have surfaced the drawer level data? I imagine it being a humidity sensor with a percentage, like the drawer level, but if there'd be a better accessory to represent this I'd be totally open to that.

Extra context on my usage: If this was a feature I would create an iOS automation to put an item for refilling the litter on my to-do list. 

Also -- I am a developer and would be happy to do some of this work. I started trying to understand your code to see if I could create a fork, but got stuck on the graphql queries.
Thanks!

**Comment by telunc** [comment]
If anyone ever look into this ticket, here's the python implementation for litter level.

https://github.com/natekspencer/pylitterbot/blob/c911033a35e2182594fd8029b2031ed0c5e025b1/pylitterbot/robot/litterrobot4.py#L164

It would probably be easier to create a new project for this python API package. It can just serve as a homebridge wrapper - similar to https://github.com/ZeliardM/homebridge-kasa-python

**Comment by rylee-s** [comment]
The graphql queries are a hoot! 

Do you have any ideas an alternative accessory types that might work better than humidity sensors? I just merged a pr that allows the waste level sensor to be disabled since it messes with the household humidity levels so I would like to use something else if it makes sense. Otherwise I can just do another set of humidity sensors :)

**Comment by caleefulling** [comment]
I could see a battery level working, assuming that wouldn't also mess with the household levels. I don't use the household levels so would be totally fine with it also being a humidity sensor if that makes more sense or is easier though.

**Comment by emroch** [comment]
You can keep the waste level from affecting the household levels by changing `Status > Include in Home Summaries` to off in the Homekit accessory settings. This takes it out of the Climate tab, but whatever room it is in does still show the humidity. I resolved that by making a "Litter-Robot" room, rather than keeping the accessories in my "Office" room. I did the same Status trick to keep the globe light from looking like a light was on in the house.

**Comment by emroch** [comment]
As for accessory types, Humidity is a workable baseline but I think these other types could work better:
- Battery:
  - BATTERY_LEVEL: level 0-100
  - STATUS_LOW_BATTERY: time to add litter/empty waste (assuming this is configurable)
  - CHARGING_STATE: would likely go unused
- Filter Maintenance:
  - FILTER_LIFE_LEVEL: level 0-100
  - FILTER_CHANGE_INDICATION: time to add litter/empty waste
  - RESET_FILTER_INDICATION: perhaps trigger manual cycle or reset?

The filter seems like a better fit to me, and also won't mess with the battery summaries in Home.
In either case, you'll probably need to represent the waste level as "remaining capacity", ie `filter_life = 100 - waste_level` so a full drawer appears as a depleted filter. Though if the change indicator is controllable on your end, maybe let the user decide if it is a count-up or count-down indicator. For litter level, the standard count-down of battery/filter fits just fine.
